### ISSUE TITLE
Ignore unmatched files option

### ISSUE THREAD

**Issue by yuheiy** [segmentio/metalsmith-ignore#14]
I'd like an option to ignore files that do not match the pattern.

```javascript
// Ignore files other than markdown
metalsmith.use(ignore({ patterns: '**/*.md', unmatch: true }));
```

**Comment by yuheiy** [comment]
I am not satisfied with `unmatch`. Do you have ideas for better name?

**Comment by woodyrew** [comment]
`invert` maybe.
Do you know you can do the following to invert your match
```js
// Ignore files other than markdown
metalsmith.use(ignore({ patterns: '!**/*.md' }));
```

**Comment by yuheiy** [comment]
Wow, I did not know that😓

I think that it is better to use it.
