### ISSUE TITLE
Does not match *~

### ISSUE THREAD

**Issue by jcoffland** [segmentio/metalsmith-ignore#3]
I tried to metalsmith-ignore to filter out emacs backup files which end with a tilda.  I added this:

```
.use(require('metalsmith-ignore')('*~'))
```

but it just doesn't work.  Files like `index.md~` still pass right through.

**Comment by jcoffland** [comment]
Why did you close this without an explanation?

**Comment by woodyrew** [comment]
Sorry, I thought the explanation would come through here. I closed via a commit that added a test that passes using the config you supplied.

metalsmith-ignore@v1.0.0 has this working.

**Comment by Ajedi32** [comment]
There _is_ an explanation:

> woodyrew closed this in 761430d 

Click the commit ID and you'll see the code change that caused this issue to be closed.
