### ISSUE TITLE
how to ignore a folder?

### ISSUE THREAD

**Issue by fizzydigital** [segmentio/metalsmith-ignore#5]
Here's my `metalsmith.json`:

```
"metalsmith-ignore": [

    "less/**",
    "less",

]
```

It ignores all `*.less` files, but still copies `less/` directory into the build folder.

Here are all the patterns I tried so far:

```
[

    "less/**/*.less",
    "less/*",
    "less/**/*",
    "less/",
    "less",
    "./less"

]
```

 Any suggestions?

**Comment by oupala** [comment]
I had the exact same problem as you.

You might have invisible dotfile in your less directory. If you also delete dotfiles, it should work.

Here is my (working) configuration:

```js
        .use(ignore([ // use ignore as soon as possible is important as it lowers the build time
            'js/bootstrap/**', // ignore bootstrap files
            'js/bootstrap/**/.*' // ignore bootstrap hidden files
        ]))
```js

Hope this helps!

**Comment by cameronjroe** [comment]
I'm also confused about this. It doesn't appear very semantic to use a glob if you simply want to ignore a directory entirely. Ideally we could just put the folder name:

```
.use(ignore([
    'directory'
]))

**Comment by oupala** [comment]
In other words, you must explicitly ignore hidden files in addition to the directory if you want to ignore an entire directory that contains hidden file.

**Comment by danicholls** [comment]
Thanks, @oupala. :+1:

**Comment by julmot** [comment]
Why not just use `Metalsmith(__dirname).ignore("folder")`?

**Comment by oupala** [comment]
Thanks @julmot for this interesting suggestion. I tried it just now and did not managed to make it work.

I replaced this:

```js
.use(ignore([
    'images/logo.svg'
]))
```

by this:

```js
.ignore(
  'images/logo.svg'
)
```

And my logo.svg file is no more ignored.

**Comment by julmot** [comment]
@oupala The `.ignore()` function will search relative from the source directory (`.source(dir)`). Are you sure that you aren't referencing from the metalsmith file? Also, `.ignore()` accepts an array too. So you don't need to replace it with a single string.

**Comment by oupala** [comment]
I think I am correctly referencing the file:

```bash
$ ls -l src/images/logo.svg 
-rw-r--r-- 1 myuser myuser 4694 juil.  2  2015 src/images/logo.svg
```

By the way, I'm also using arrays when I need to ignore more than one item.

**Comment by julmot** [comment]
@oupala For me, it works like a charm.

**Comment by oupala** [comment]
Well, for me, it really doesn't... :-)

Does anyone has an idea about why it doesn't work in some cases, and which ones?

**Comment by julmot** [comment]
@oupala Did you tried other filenames? Can you please post your full code that is necessary to execute Metalsmith?

Regarding your question, I think this plugin still exists due to compatibility reasons.

**Comment by oupala** [comment]
When using `ignore`, it appears that we can use full path to the file. We need to use the ** prefix.

These syntaxes works:

```js
.ignore([
      '**/src/images/logo.svg'
])
```

```js
.ignore([
      '**/images/logo.svg'
])
```

```js
.ignore([
      '**/logo.svg'
])
```

```js
.ignore([
      'logo.svg'
])
```

But it seems that - if you wan to add some dir in the path, the path **must** be prepended by `**`.

Is there a way to specify a path relative to the source directory? Something like:

```js
.ignore([
      'images/logo.svg'
])
```

or

```js
.ignore([
      'src/images/logo.svg'
])
```

**Comment by marcoms** [comment]
Thanks @oupala for that, ignoring a directory now works for me!
