### ISSUE TITLE
Does this support ignoring dot files?

### ISSUE THREAD

**Issue by andy-hook** [segmentio/metalsmith-ignore#7]
I can't seem to ignore the .htaccess inside my src directory, I add it to the array of directories and yet it is still output into the build folder..

**Comment by benpolinsky** [comment]
'ello.

Ever figure this one out?  I know it's been quite a while, but I'm running into the same problem with regards to random dot files inside of node_modules

**Comment by benpolinsky** [comment]
Ah, I got it. 
Here's what I used:

`['node_modules/**/*', '**/node_modules/**/*', '**/node_modules/.*']`

**Comment by andy-hook** [comment]
Yeah it was a schoolboy error if I remember. Was quite some time ago now though.
