### ISSUE TITLE
metalsmith-ignore should be deprecated?

### ISSUE THREAD

**Issue by misterbrownlee** [segmentio/metalsmith-ignore#8]
Hi -

I think this might do well to be deprecated and dropped from the main metalsmith documentation?  Per #5, the core of metalsmith includes an `ignore()` function that accomplishes the same functionality is this plugin.

**Comment by ccesare** [comment]
I think the behavior of the core `ignore()` is different. Do calls to `.ignore()` get added to the plugin stack like calls to `.use()` do?

I have a workflow that needs to ignore some files and directories, but only after I've already processed them with custom plugins. No matter how far down in the call order I placed `.ignore()`, I could never get it to behave like I expected. Calls to `.use(ignore())` do give me the behavior I expect, and they clearly get added to the plugin stack.

As far as I can tell, core `ignore()` doesn't respect the order in which it's called, which won't work for my use case.

**Comment by woodyrew** [comment]
Behaviour is different
